### ISSUE TITLE
cocoapods

### ISSUE THREAD

**Issue by 0x1306a94** [indragiek/CocoaMarkdown#42] opened 2016-12-20 06:41 UTC
pod search CocoaMarkdown
[!] Unable to find a pod with name, author, summary, or description matching `CocoaMarkdown`

**Comment by pronebird** [comment] 2017-07-30 18:14
Seriously though, why not to publish to CocoaPods when pod spec is already there?

**Comment by tataevr** [comment] 2018-06-01 15:26
pod "CocoaMarkdown", :git => 'https://github.com/indragiek/CocoaMarkdown.git'
Just explicitly specialize

**Comment by indragiek** [comment] 2019-10-20 00:24
Duplicate of #39, I'll keep that one open to track pushing the spec to trunk.

**Closed by indragiek** 2019-10-20 00:24 UTC

**Comment by rizwan95** [comment] 2020-02-26 13:02
Anyone who wants to use this awesome framework, you just have to specify the pod name in your podfile. Specifying the CocoaMarkdown's git url in your podfile will point to version 1.0 and it will cause errors.
Example
` pod 'CocoaMarkdown'`

**Comment by rizwan95** [comment] 2020-02-26 13:02
> pod "CocoaMarkdown", :git => 'https://github.com/indragiek/CocoaMarkdown.git'
> Just explicitly specialize source and that will do the trick.

Looks like the repo doesn't update the recent changes in cocoapods, yet.

Anyone who wants to use this awesome framework, please use the path https://github.com/LetaiefAymen/CocoaMarkdown.git until the authors make the changes in the podspec.

Example
pod "CocoaMarkdown", :git => 'https://github.com/LetaiefAymen/CocoaMarkdown.git'
